#!/bin/ash
#
# ipv6_updater
#
# paremeters:
#   $1 = local_hostname (eg. myserver.lan)
#   $2 = internet_hostname (eg. myserver.example.com)

if [ "$#" -ne 2 ]; then
    echo "Usage -> ipv6_updater lan_hostname internet_hostname"
    exit 1
fi

# Get the USERNAME, PASSWORD, AND BASE_URL from config file
CONF_PATH=$(dirname "$(readlink -f "$0")")
. "$CONF_PATH/ipv6_updater.conf"

IP=$(dig +short AAAA $1 @localhost | grep -v '^fd' | grep :)

if [ $? -eq 0 ]; then
  curl -s "$BASE_URL?u=$USERNAME&p=$PASSWORD&h=$2&ip=$IP"
fi
